apiVersion: v1
kind: Config

clusters: # array 
- name: kube-clusters
  clusters:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    #certifiacte-authority-date: after encoding base64 
    server: https://kube-clusters:6443

contexts: # array 

- name: kube-admin@kube-clusters
  context:
    cluster: kube-clusters
    user: my-kube-admin
    namespace: my-namespace
users: # array 
- name: my-kube-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key